refactor: change the release workflow to run upon closed PRs to master

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
     types:
       - closed
-    branches: [release]
+    branches: [master]
 
 permissions:
   id-token: write
@@ -16,14 +16,68 @@ env:
   PROJECT_NAME: maive
 
 jobs:
+  labelChecks:
+    runs-on: ubuntu-latest
+
+    outputs:
+      READY_TO_BUILD: ${{ steps.labelCheck.outputs.READY_TO_BUILD }}
+      SEMVER_LEVEL: ${{ steps.labelCheck.outputs.SEMVER_LEVEL }}
+
+    steps:
+      - name: Determine labels from PR
+        id: labelCheck
+        run: |
+          label_names='${{ toJson(github.event.pull_request.labels) }}'
+
+          ready_to_build="false"
+
+          declare -A label_map=(
+            ["release:next-version"]="release"
+          )
+
+          for label in "${!label_map[@]}"; do
+            if echo "$label_names" | jq -e ".[] | select(.name == \"$label\")" >/dev/null; then
+              eval "${label_map[$label]}=true"
+            fi
+          done
+
+          semver_labels=$(echo "$label_names" | jq -r '[.[] | select(.name | startswith("v-")) | .name]')
+          label_count=$(echo "$semver_labels" | jq 'length')
+
+          semver_level="build"
+          if ((label_count > 1)); then
+            echo "Error: more than one label starting with 'v-' found." >&2
+            exit 1
+          elif ((label_count == 1)); then
+            semver_level=$(echo "$semver_labels" | jq -r '.[0]' | sed 's/^v-//')
+            echo "Assigned semver level: $semver_level"
+          fi
+
+          # convert to uppercase
+          semver_level=$(echo "$semver_level" | tr '[:lower:]' '[:upper:]')
+
+          echo "READY_TO_BUILD=$ready_to_build" >> "$GITHUB_OUTPUT"
+          echo "SEMVER_LEVEL=$semver_level" >> "$GITHUB_OUTPUT"
+        shell: bash
+
   build:
-    if: github.event.pull_request.merged == true
+    needs: [labelChecks]
+    if: ${{ needs.labelChecks.outputs.READY_TO_BUILD == 'true' && github.event.pull_request.merged == true }}
     strategy:
       matrix:
         service: [react-ui, flask-api, r-plumber]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+        with:
+          ref: master
+
+      - name: Bump version
+        id: bumpVersion
+        uses: ./.github/actions/composite/bumpVersion
+        with:
+          SEMVER_LEVEL: ${{ needs.labelChecks.outputs.SEMVER_LEVEL }}
+          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
 
       - uses: aws-actions/configure-aws-credentials@v4
         with:
